time-between-games: 300
auto-end-time: 30
cancel-winning-messages: true
database:
    host: localhost
    port: 3306
    database: database
    user: user
    password: pass
game-config:
    MATH:
        supplementary-file: problems.txt
        command-rewards:
            1:
            - eco give %player% 1500
            - broadcast &a%player%&7 answered &a%place%&7 in &a%time%&7 seconds!
            2:
            - eco give %player% 1000
            - broadcast &a%player%&7 answered &a%place%&7 in &a%time%&7 seconds!
            3:
            - eco give %player% 500
            - broadcast &a%player%&7 answered &a%place%&7 in &a%time%&7 seconds!
    HOVER:
        supplementary-file: words.txt
        command-rewards:
            1:
            - eco give %player% 1500
            - broadcast &a%player%&7 answered &a%place%&7 in &a%time%&7 seconds!
            2:
            - eco give %player% 1000
            - broadcast &a%player%&7 answered &a%place%&7 in &a%time%&7 seconds!
            3:
            - eco give %player% 500
            - broadcast &a%player%&7 answered &a%place%&7 in &a%time%&7 seconds!
    UNSCRAMBLE:
        supplementary-file: words.txt
        command-rewards:
            1:
            - eco give %player% 1500
            - broadcast &a%player%&7 answered &a%place%&7 in &a%time%&7 seconds!
            2:
            - eco give %player% 1000
            - broadcast &a%player%&7 answered &a%place%&7 in &a%time%&7 seconds!
            3:
            - eco give %player% 500
            - broadcast &a%player%&7 answered &a%place%&7 in &a%time%&7 seconds!
    HANGMAN:
        supplementary-file: words.txt
        command-rewards:
            1:
            - eco give %player% 1500
            - broadcast &a%player%&7 answered &a%place%&7 in &a%time%&7 seconds!
            2:
            - eco give %player% 1000
            - broadcast &a%player%&7 answered &a%place%&7 in &a%time%&7 seconds!
            3:
            - eco give %player% 500
            - broadcast &a%player%&7 answered &a%place%&7 in &a%time%&7 seconds!
        dash-percentage: 0.5
language:
    TYPE_START:
    - <hover:show_text:'<white><word>'><green>Games <dark_gray>» <green>Hover and type the word!
    MATH_START:
    - <hover:show_text:'<white><word>'><green>Games <dark_gray>» <green>Hover and solve the math problem!
    UNSCRAMBLE_START:
    - <hover:show_text:'<white><word>'><green>Games <dark_gray>» <green>Hover and unscramble the word!
    HANGMAN_START:
    - <hover:show_text:'<white><word>'><green>Games <dark_gray>» <green>Hover and fill in the blanks!
    UNSCRAMBLE_INCOMPLETE:
    - <green>Games <dark_gray>» <gray>Game ended. Winners\: <winners>
    HANGMAN_INCOMPLETE:
    - <green>Games <dark_gray>» <gray>Game ended. Winners\: <winners>
    TYPE_INCOMPLETE:
    - <green>Games <dark_gray>» <gray>Game ended. Winners\: <winners>
    MATH_INCOMPLETE:
    - <green>Games <dark_gray>» <gray>Game ended. Winners\: <winners>
    FAILURE:
    - <green>Games <dark_gray>» <gray>Nobody typed <green><word><gray> in time!
    WINNERS_FORMAT:
    - '<green><name><gray>[<green><time>s<gray>]'
    WINNERS_SEPARATOR:
    - ', '
require-player-count: false
minimum-players: 1
